### ISSUE TITLE
rpt_Scenario_1.Rmd failed to knit

### ISSUE THREAD

**Issue by rato-li** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#9]
Quitting from lines 22-179 (rpt_Scenario_1.Rmd) 
Error in db_connect_from_config(myconfig) : 
  could not find function "db_connect_from_config"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted

**Comment by Marco-Sulser** [comment]
Hi Rato, I have noticed you haven't set any code chunk options. A good resource is: https://yihui.org/knitr/options/. 

Give me a buzz, if you want me to try out some for you.

**Comment by kevingyk6854** [comment]
This because db_connect_from_config() function is not in the connection tool package anymore. The function was renamed back as db_connect(). I have already uploaded the new html for your rpt_Scenario_1.Rmd and fixed that problem. Please check it. 
If you wanna play around with ggplot2, I have already created two plots under this path `code/src/annual_Scenario_1.Rmd`.
Cheers.

**Comment by rato-li** [comment]
Thanks. Issue resovled.

**Comment by rato-li** [comment]
I can knit the document now. Thanks Yukai.
